name: k6 load test
on: [push]
permissions:
  contents: write
jobs:
      build: k6 load test
      runs-on: ubuntu-latest
  steps: 
    - name: step 1 - checkout
      uses: actions/checkout@v


    - name: step 2 - run k6 load test
      uses: grafana/k6-action@v0.3.1
      with: 
        filename: k6-aws/exemploaws1.js